name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build for all platforms
      run: |
        mkdir -p dist

        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -v -ldflags="-s -w -X main.Version=${{ steps.get_version.outputs.VERSION }}" -o dist/wsdl2api-linux-amd64 ./cmd/wsdl2api
        tar czf dist/wsdl2api-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz -C dist wsdl2api-linux-amd64

        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -v -ldflags="-s -w -X main.Version=${{ steps.get_version.outputs.VERSION }}" -o dist/wsdl2api-linux-arm64 ./cmd/wsdl2api
        tar czf dist/wsdl2api-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.gz -C dist wsdl2api-linux-arm64

        # macOS AMD64
        GOOS=darwin GOARCH=amd64 go build -v -ldflags="-s -w -X main.Version=${{ steps.get_version.outputs.VERSION }}" -o dist/wsdl2api-darwin-amd64 ./cmd/wsdl2api
        tar czf dist/wsdl2api-${{ steps.get_version.outputs.VERSION }}-darwin-amd64.tar.gz -C dist wsdl2api-darwin-amd64

        # macOS ARM64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -v -ldflags="-s -w -X main.Version=${{ steps.get_version.outputs.VERSION }}" -o dist/wsdl2api-darwin-arm64 ./cmd/wsdl2api
        tar czf dist/wsdl2api-${{ steps.get_version.outputs.VERSION }}-darwin-arm64.tar.gz -C dist wsdl2api-darwin-arm64

        # Windows AMD64
        GOOS=windows GOARCH=amd64 go build -v -ldflags="-s -w -X main.Version=${{ steps.get_version.outputs.VERSION }}" -o dist/wsdl2api-windows-amd64.exe ./cmd/wsdl2api
        zip -j dist/wsdl2api-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip dist/wsdl2api-windows-amd64.exe

    - name: Generate checksums
      run: |
        cd dist
        sha256sum *.tar.gz *.zip > checksums.txt

    - name: Generate changelog
      id: changelog
      run: |
        # Get the previous tag
        PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")

        if [ -z "$PREVIOUS_TAG" ]; then
          echo "First release"
          CHANGELOG="Initial release of wsdl2api"
        else
          CHANGELOG=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s" --no-merges)
        fi

        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Changes
          ${{ steps.changelog.outputs.CHANGELOG }}

          ## Installation

          ### Linux (AMD64)
          ```bash
          wget https://github.com/thdev01/wsdl2api/releases/download/${{ steps.get_version.outputs.VERSION }}/wsdl2api-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz
          tar xzf wsdl2api-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz
          sudo mv wsdl2api-linux-amd64 /usr/local/bin/wsdl2api
          ```

          ### macOS (Apple Silicon)
          ```bash
          wget https://github.com/thdev01/wsdl2api/releases/download/${{ steps.get_version.outputs.VERSION }}/wsdl2api-${{ steps.get_version.outputs.VERSION }}-darwin-arm64.tar.gz
          tar xzf wsdl2api-${{ steps.get_version.outputs.VERSION }}-darwin-arm64.tar.gz
          sudo mv wsdl2api-darwin-arm64 /usr/local/bin/wsdl2api
          ```

          ### Windows
          Download and extract `wsdl2api-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip`

          ## Verification
          Verify the checksums match:
          ```bash
          sha256sum -c checksums.txt
          ```

          ---
          **Full Changelog**: https://github.com/thdev01/wsdl2api/compare/${{ steps.get_version.outputs.VERSION }}
        files: |
          dist/*.tar.gz
          dist/*.zip
          dist/checksums.txt
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [create-release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: github.event_name != 'pull_request'

    - name: Get version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          thdev01/wsdl2api:${{ steps.get_version.outputs.VERSION }}
          thdev01/wsdl2api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
